interface IControlButton {
  name: string;
  view: 'ghost' | 'primary' | 'secondary' | 'clear';
  color?: 'green' | 'red' | 'purple';
}

const ACCORDANCE_BUTTON_NAMES_TO_STRINGS = {
  POW: '^',
  e: String(Math.E),
  π: String(Math.PI),
  round: 'round(',
  ABS: 'abs(',
  SIN: 'sin(',
  COS: 'cos(',
  TAN: 'tan(',
  LOG: ')log(',
  LN: 'ln(',
  LG: 'lg(',
  SQRT: 'sqrt(',
  if: 'if (',
  then: ') then (',
  else: ') else (',
  or: ') || (',
  and: ') && (',
};

const BUTTONS: IControlButton[] = [
  { name: 'SIN', view: 'ghost' },
  { name: 'SQRT', view: 'ghost' },
  { name: 'LOG', view: 'ghost' },
  { name: '>', view: 'ghost', color: 'purple' },
  { name: '===', view: 'ghost', color: 'purple' },
  { name: 'if', view: 'ghost', color: 'purple' },
  { name: '7', view: 'primary' },
  { name: '8', view: 'primary' },
  { name: '9', view: 'primary' },
  { name: '/', view: 'secondary' },
  { name: 'C', view: 'secondary', color: 'red' },
  { name: 'COS', view: 'ghost' },
  { name: 'POW', view: 'ghost' },
  { name: 'LG', view: 'ghost' },
  { name: '>=', view: 'ghost', color: 'purple' },
  { name: '!==', view: 'ghost', color: 'purple' },
  { name: 'then', view: 'ghost', color: 'purple' },
  { name: '4', view: 'primary' },
  { name: '5', view: 'primary' },
  { name: '6', view: 'primary' },
  { name: '*', view: 'secondary' },
  { name: '<-', view: 'secondary', color: 'red' },
  { name: 'TAN', view: 'ghost' },
  { name: 'round', view: 'ghost' },
  { name: 'LN', view: 'ghost' },
  { name: '<', view: 'ghost', color: 'purple' },
  { name: 'and', view: 'ghost', color: 'purple' },
  { name: 'else', view: 'ghost', color: 'purple' },
  { name: '1', view: 'primary' },
  { name: '2', view: 'primary' },
  { name: '3', view: 'primary' },
  { name: '-', view: 'secondary' },
  { name: '(', view: 'secondary' },
  { name: 'ABS', view: 'ghost' },
  { name: '\u03C0', view: 'ghost' },
  { name: 'e', view: 'ghost' },
  { name: '<=', view: 'ghost', color: 'purple' },
  { name: 'or', view: 'ghost', color: 'purple' },
  { name: '?', view: 'ghost', color: 'purple' },
  { name: '0', view: 'primary' },
  { name: '.', view: 'primary' },
  { name: 'CALC', view: 'ghost', color: 'green' },
  { name: '+', view: 'secondary' },
  { name: ')', view: 'secondary' },
];

export { ACCORDANCE_BUTTON_NAMES_TO_STRINGS, BUTTONS };
